
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.25.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace SCCC {
    using System;
    using Terminal.Gui;
    
    
    public partial class MyView : Terminal.Gui.Window {
        
        private Terminal.Gui.ColorScheme redOnBlack;
        
        private Terminal.Gui.ColorScheme greyOnBlack;
        
        private Terminal.Gui.ColorScheme blueOnBlack;
        
        private Terminal.Gui.ColorScheme tgDefault;
        
        private Terminal.Gui.Label label1;
        
        private Terminal.Gui.Label status;
        
        private Terminal.Gui.Button reset;
        
        private Terminal.Gui.TableView tableView;
        
        private Terminal.Gui.Button start;
        
        private Terminal.Gui.Button connect;
        
        private Terminal.Gui.Button path;
        
        private Terminal.Gui.Label time;
        
        private Terminal.Gui.Button sync;
        
        private Terminal.Gui.Label date;
        
        private Terminal.Gui.Label tZeroLabel;
        
        private Terminal.Gui.Button setT0;
        
        private Terminal.Gui.Button clearT0;
        
        private void InitializeComponent() {
            this.clearT0 = new Terminal.Gui.Button();
            this.setT0 = new Terminal.Gui.Button();
            this.tZeroLabel = new Terminal.Gui.Label();
            this.date = new Terminal.Gui.Label();
            this.sync = new Terminal.Gui.Button();
            this.time = new Terminal.Gui.Label();
            this.path = new Terminal.Gui.Button();
            this.connect = new Terminal.Gui.Button();
            this.start = new Terminal.Gui.Button();
            this.tableView = new Terminal.Gui.TableView();
            this.reset = new Terminal.Gui.Button();
            this.status = new Terminal.Gui.Label();
            this.label1 = new Terminal.Gui.Label();
            this.redOnBlack = new Terminal.Gui.ColorScheme();
            this.redOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Red, Terminal.Gui.Color.Black);
            this.redOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightRed, Terminal.Gui.Color.Black);
            this.redOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Red, Terminal.Gui.Color.Brown);
            this.redOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightRed, Terminal.Gui.Color.Brown);
            this.redOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Gray, Terminal.Gui.Color.Black);
            this.greyOnBlack = new Terminal.Gui.ColorScheme();
            this.greyOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.greyOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.greyOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.DarkGray);
            this.greyOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.DarkGray);
            this.greyOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.blueOnBlack = new Terminal.Gui.ColorScheme();
            this.blueOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightBlue, Terminal.Gui.Color.Black);
            this.blueOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Cyan, Terminal.Gui.Color.Black);
            this.blueOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightBlue, Terminal.Gui.Color.BrightYellow);
            this.blueOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Cyan, Terminal.Gui.Color.BrightYellow);
            this.blueOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Gray, Terminal.Gui.Color.Black);
            this.tgDefault = new Terminal.Gui.ColorScheme();
            this.tgDefault.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Blue);
            this.tgDefault.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightCyan, Terminal.Gui.Color.Blue);
            this.tgDefault.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.Gray);
            this.tgDefault.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightBlue, Terminal.Gui.Color.Gray);
            this.tgDefault.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Brown, Terminal.Gui.Color.Blue);
            this.Width = 140;
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Visible = true;
            this.ColorScheme = this.tgDefault;
            this.Modal = false;
            this.IsMdiContainer = false;
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.Border.Effect3D = true;
            this.Border.Effect3DBrush = null;
            this.Border.DrawMarginFrame = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = "Press Ctrl+Q to quit";
            this.label1.Width = 4;
            this.label1.Height = 1;
            this.label1.X = 0;
            this.label1.Y = 0;
            this.label1.Visible = true;
            this.label1.Data = "label1";
            this.label1.Text = "Starship Controller Command Center";
            this.label1.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label1);
            this.status.Width = 10;
            this.status.Height = 1;
            this.status.X = Pos.Left(reset) - 11;
            this.status.Y = 0;
            this.status.Visible = true;
            this.status.Data = "status";
            this.status.Text = "UNKNOWN";
            this.status.TextAlignment = Terminal.Gui.TextAlignment.Right;
            this.Add(this.status);
            this.reset.Width = 9;
            this.reset.Height = 1;
            this.reset.X = Pos.AnchorEnd(10);
            this.reset.Y = 0;
            this.reset.Visible = true;
            this.reset.ColorScheme = this.redOnBlack;
            this.reset.Data = "reset";
            this.reset.Text = "RESET";
            this.reset.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.reset.IsDefault = false;
            this.Add(this.reset);
            this.tableView.Width = Dim.Fill(1);
            this.tableView.Height = Dim.Fill(1);
            this.tableView.X = Pos.Right(connect) + 1;
            this.tableView.Y = 1;
            this.tableView.Visible = true;
            this.tableView.Data = "tableView";
            this.tableView.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.tableView.FullRowSelect = true;
            this.tableView.Style.AlwaysShowHeaders = true;
            this.tableView.Style.ExpandLastColumn = true;
            this.tableView.Style.InvertSelectedCellFirstCharacter = false;
            this.tableView.Style.ShowHorizontalHeaderOverline = true;
            this.tableView.Style.ShowHorizontalHeaderUnderline = true;
            this.tableView.Style.ShowVerticalCellLines = true;
            this.tableView.Style.ShowVerticalHeaderLines = true;
            System.Data.DataTable tableViewTable;
            tableViewTable = new System.Data.DataTable();
            System.Data.DataColumn tableViewTableAbsTime;
            tableViewTableAbsTime = new System.Data.DataColumn();
            tableViewTableAbsTime.ColumnName = "Abs. Time";
            tableViewTable.Columns.Add(tableViewTableAbsTime);
            System.Data.DataColumn tableViewTableRelTime;
            tableViewTableRelTime = new System.Data.DataColumn();
            tableViewTableRelTime.ColumnName = "Rel. Time";
            tableViewTable.Columns.Add(tableViewTableRelTime);
            System.Data.DataColumn tableViewTableDetails;
            tableViewTableDetails = new System.Data.DataColumn();
            tableViewTableDetails.ColumnName = "Details";
            tableViewTable.Columns.Add(tableViewTableDetails);
            this.tableView.Table = tableViewTable;
            this.Add(this.tableView);
            this.start.Width = 16;
            this.start.Height = 1;
            this.start.X = 1;
            this.start.Y = 2;
            this.start.Visible = true;
            this.start.Data = "start";
            this.start.Text = "Start SCCC-S";
            this.start.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.start.IsDefault = false;
            this.Add(this.start);
            this.connect.Width = 21;
            this.connect.Height = 1;
            this.connect.X = Pos.Right(start) + 1;
            this.connect.Y = 2;
            this.connect.Visible = true;
            this.connect.Data = "connect";
            this.connect.Text = "Connect to SCCC-S";
            this.connect.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.connect.IsDefault = false;
            this.Add(this.connect);
            this.path.Width = 8;
            this.path.Height = 1;
            this.path.X = Pos.Top(start) - 1;
            this.path.Y = 4;
            this.path.Visible = true;
            this.path.Data = "path";
            this.path.Text = "Path";
            this.path.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.path.IsDefault = false;
            this.Add(this.path);
            this.time.Width = 25;
            this.time.Height = 1;
            this.time.X = 11;
            this.time.Y = 4;
            this.time.Visible = true;
            this.time.Data = "time";
            this.time.Text = "00:00:00 CST // 00:00:00 CET";
            this.time.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.time);
            this.sync.Width = 8;
            this.sync.Height = 1;
            this.sync.X = Pos.Top(start) - 1;
            this.sync.Y = 6;
            this.sync.Visible = true;
            this.sync.Data = "sync";
            this.sync.Text = "Sync";
            this.sync.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.sync.IsDefault = false;
            this.Add(this.sync);
            this.date.Width = 7;
            this.date.Height = 1;
            this.date.X = 11;
            this.date.Y = 6;
            this.date.Visible = true;
            this.date.Data = "date";
            this.date.Text = "11/11/23";
            this.date.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.date);
            this.tZeroLabel.Width = 11;
            this.tZeroLabel.Height = 1;
            this.tZeroLabel.X = 28;
            this.tZeroLabel.Y = 6;
            this.tZeroLabel.Visible = true;
            this.tZeroLabel.Data = "tZeroLabel";
            this.tZeroLabel.Text = "T- 69:42:00";
            this.tZeroLabel.TextAlignment = Terminal.Gui.TextAlignment.Right;
            this.Add(this.tZeroLabel);
            this.setT0.Width = 18;
            this.setT0.Height = 3;
            this.setT0.X = 1;
            this.setT0.Y = 8;
            this.setT0.Visible = true;
            this.setT0.Data = "setT0";
            this.setT0.Text = "Set T0";
            this.setT0.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.setT0.IsDefault = false;
            this.Add(this.setT0);
            this.clearT0.Width = 20;
            this.clearT0.Height = 3;
            this.clearT0.X = 19;
            this.clearT0.Y = 8;
            this.clearT0.Visible = true;
            this.clearT0.Data = "clearT0";
            this.clearT0.Text = "Clear T0";
            this.clearT0.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.clearT0.IsDefault = false;
            this.Add(this.clearT0);
        }
    }
}
